### ISSUE TITLE
streamlit hello --- error

### ISSUE THREAD

**Issue by chd1998** [streamlit/demo-self-driving#4]
'gbk' codec can't decode byte 0x94 in position 9229: illegal multibyte sequence

**Comment by treuille** [comment]
Thank you for the bug @chd1998 ! I'm sorry you had this problem. In order for us to better understand and resolve your problem, could you please [submit a bug report](https://github.com/streamlit/streamlit/issues/new?assignees=&labels=bug&template=bug_report.md&title=) over at `streamlit/streamlit` because:

1. That bug report form contains a number of useful questions which we can use to diagnose your issue.
2. That repo is checked much more often. (I'm really sorry we missed you here!)

Thanks for using Streamlit! :)

**Comment by treuille** [comment]
Thank you for the bug @chd1998 ! I'm sorry you had this problem. In order for us to better understand and resolve your problem, could you please [submit a bug report](https://github.com/streamlit/streamlit/issues/new?assignees=&labels=bug&template=bug_report.md&title=) over at `streamlit/streamlit` because:

1. That bug report form contains a number of useful questions which we can use to diagnose your issue.
2. That repo is checked much more often. (I'm really sorry we missed you here!)

Thanks for using Streamlit! :)
